language: go
install: cd ~ && wget https://github.com/spf13/hugo/releases/download/v0.14/hugo_0.14_amd64.deb && sudo dpkg -i hugo*.deb && hugo version
after_install: cd $HOME/gopath/src/github.com/marcotroisi/blog
script: 
  - git config --global user.email "hello@marcotroisi.com"
  - git config --global user.name "Travis CI"
  - git remote remove origin
  - git remote add origin https://$GH_TOKEN@github.com/marcotroisi/blog.git
after_success:
  - ./deploy.sh
