sudo: required
language: go
services:
  - docker
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull marcotroisi/hugo:0.17
install: cd ~ docker run -v `pwd`:/website  marcotroisi/hugo:0.17 version
script: 
  - cd $HOME/gopath/src/github.com/marcotroisi/blog
  - git config --global user.email "hello@marcotroisi.com"
  - git config --global user.name "Travis CI"
  - git remote remove origin
  - git remote add origin https://$GH_TOKEN@github.com/marcotroisi/blog.git
  - ./deploy.sh

branches:
  only:
  - master
